name: 'Omega '
favicon: null
layout_spectrum: 0.22870262921787798
typography_spectrum: 0.19104630406945944
title: 'Omega Private Limited, Pakistan'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9384003509767354
  lightness: 0.44137456943280995
  saturation: 0.24158191960304976
  rhythmicContrast: 0.4622971012722701
purpose: []
